#!/bin/bash
#bin2assemblerdata.sh - Converts binary data to !byte-statements
#
# Copyright (c) 2015, Marcel Dümmel <marcel.duemmel@aquasign.net>
# All rights reserved.
#
# This program is licensed unter the terms of the BSD license as following:
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#   o Redistributions of source code must retain the above copyright notice,
#     this list of conditions and the following disclaimer.
#
#   o Redistributions in binary form must reproduce the above copyright notice,
#     this list of conditions and the following disclaimer in the documentation
#     and/or other materials provided with the distribution.
#
#   o Neither the name of my organizations nor the names of its contributors
#     may be used to endorse or promote products derived from this software
#     without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.


#default values
BYTESPERLINE=16
PSEUDOOPCODE="!byte"

function usage {
	echo ""
	echo "Usage: $(basename $0) [-p <s>] [-w <n>] filename"
	echo ""
	echo "This tool converts binary data to !byte-lines suitable for the Assemblers"
	echo "The default is compatible to the ACME-crossassembler. But you may alter this"
	echo "using the p-option."
	echo ""
	echo "   -p <s>    pseudo-opcode to use. (Default: $PSEUDOOPCODE)"
	echo "             depending on your shell you may have to mask some symbols (like"
	echo "             exclamation marks) with a backslash. (e.g. '\!by')"
	echo "   -w <n>    Number of Bytes per line. (Default: $BYTESPERLINE)"
	echo ""
	exit 0
}

#Read command line options
while getopts "hp:w:" opt; do
	case $opt in
		h)
			usage
			;;
		p)
			PSEUDOOPCODE="$OPTARG"
			;;
		w)
			BYTESPERLINE=$OPTARG
			;;
		\?)
			echo "Invalid option: -$OPTARG"
			exit 1
			;;
	esac
done

shift "$((OPTIND-1))"
FILE=$@

od -t x1 -v -w$BYTESPERLINE "$FILE"  | sed -n '$!s/^.\{8\}//p' | sed -e 's/^ *//;s/ *$//;s/ \{1,\}/, /g' | awk -v op="$PSEUDOOPCODE" '{print op" " $0;}'
